### ISSUE TITLE
querying for the GPU vendor & name

### ISSUE THREAD

**Issue by k-ronny** [gantoreno/macfetch#1]
hi,

maybe you can use something like that:

```
use iron_oxide::CGDirectDisplayCopyCurrentMetalDevice;

pub fn gpu() -> ColoredString {
    let display = CGDisplay::new(unsafe { CGMainDisplayID() });
    let mtl_device = unsafe { CGDirectDisplayCopyCurrentMetalDevice(display.id) };
    let gpu = unsafe { mtl_device.get_name().to_string() };

    return titled_segment("GPU", gpu);
}
```

best regards,
ronny

**Comment by gantoreno** [comment]
Ronny, I just want to say thank you for suggesting this solution! I tested it on my machine and works fantastic.

Would you like to submit a PR? Or is it okay for me to just add this to the code and draft a new release? Either way, you'll still get credited in the docs and the release notes. (:

**Comment by k-ronny** [comment]
Hi,
just use those few lines, it is okay for me.
And I have three small comments:
- it also runs on Apple Silicon!
- there is no error handling if the terminal has no `TERM_PROGRAM` but only `TERM` or nothing
- there is also no error handling if there is no battery

But anyway, it runs great, good job, thank you!

```
                    'c.           k_ronny@pollux
                 ,xNMM.           --------------
               .OMMMMo            OS: macOS 13.2.1
               OMMM0,             Host: Macmini9,1
     .;loddo:' loolloddol;.       Kernel: 22.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:     Uptime: 15 days, 3 hours, 30 minutes
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.     Packages: 234 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.       Shell: /bin/zsh
;MMMMMMMMMMMMMMMMMMMMMMMM:        Resolution: 2560x1440
:MMMMMMMMMMMMMMMMMMMMMMMM:        DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.       WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Terminal: Apple_Terminal
.XMMMMMMMMMMMMMMMMMMMMMMMMMMk     CPU: Apple M1
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.    GPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd      Battery: no battery
     ;KMMMMMMMWXXWMMMMMMMk.       Memory: 4052MiB / 16384MiB
       .cooc,.    .,coo:.         
                                                          
```

**Comment by gantoreno** [comment]
Thanks! Yeah, I coded the rust version on my M1 Mac, so Apple Silicon works fantastic. I'll add those small changes and work around some error handling for that. 👍🏻
